definitions:
  dto.AdminLoginInput:
    properties:
      password:
        example: password
        type: string
      username:
        description: |-
          如果 validate 设置为 required，则会用 gin 提供的 validator 去进行校验
          可以在 validate 后面添加自定义验证器, 参见 middleware.validator.go
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  dto.AdminLoginOutput:
    properties:
      token:
        type: string
    type: object
  dto.ServiceListOutput:
    properties:
      service_list:
        items:
          $ref: '#/definitions/dto.SingleService'
        type: array
      total_services:
        type: integer
    required:
    - service_list
    - total_services
    type: object
  dto.SingleService:
    properties:
      id:
        description: id
        type: integer
      load_type:
        description: 类型
        type: integer
      qpd:
        description: qpd
        type: integer
      qps:
        description: qps
        type: integer
      service_address:
        description: 服务地址
        type: string
      service_desc:
        description: 服务描述
        type: string
      service_name:
        description: 服务名称
        type: string
      total_node:
        description: 节点数
        type: integer
    type: object
  middleware.Response:
    properties:
      data:
        type: object
      errmsg:
        type: string
      errno:
        type: integer
      stack:
        type: object
      trace_id:
        type: object
    type: object
info:
  contact: {}
paths:
  /admin/info:
    get:
      consumes:
      - application/json
      description: Admin Info 接口
      operationId: /admin/info
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminLoginOutput'
              type: object
      summary: Admin Info
      tags:
      - 管理员接口
    post:
      consumes:
      - application/json
      description: Admin 修改密码接口
      operationId: /admin/info/change_password
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminLoginOutput'
              type: object
      summary: Admin Change Password
      tags:
      - 管理员接口
  /admin/login:
    post:
      consumes:
      - application/json
      description: Admin Login 接口
      operationId: /admin/login
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AdminLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.AdminLoginOutput'
              type: object
      summary: Admin Login
      tags:
      - 管理员接口
  /admin/logout:
    get:
      consumes:
      - application/json
      description: Admin Log out 接口
      operationId: /admin/logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Admin Log out
      tags:
      - 管理员接口
  /service/delete:
    get:
      consumes:
      - application/json
      description: 删除一个服务
      operationId: /service/delete
      parameters:
      - description: 服务 ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Delete service
      tags:
      - 服务管理
  /service/service_list:
    get:
      consumes:
      - application/json
      description: 服务列表
      operationId: /service/service_list
      parameters:
      - description: 关键词
        in: query
        name: keyword
        type: string
      - description: 每页个数
        in: query
        name: page_size
        required: true
        type: integer
      - description: 总页数
        in: query
        name: page_number
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ServiceListOutput'
              type: object
      summary: Service List
      tags:
      - 服务管理
swagger: "2.0"
