definitions:
  dto.AdminLoginInput:
    properties:
      password:
        example: password
        type: string
      username:
        description: |-
          如果 validate 设置为 required，则会用 gin 提供的 validator 去进行校验
          可以在 validate 后面添加自定义验证器, 参见 middleware.validator.go
        example: admin
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /admin/info:
    get:
      consumes:
      - application/json
      description: Admin Login 接口
      operationId: /admin/info
      produces:
      - application/json
      summary: Admin Login
      tags:
      - 管理员登陆接口
  /admin/login:
    post:
      consumes:
      - application/json
      description: Admin Login 接口
      operationId: /admin/login
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.AdminLoginInput'
      produces:
      - application/json
      summary: Admin Login
      tags:
      - 管理员登陆接口
  /admin/logout:
    get:
      consumes:
      - application/json
      description: Admin Log out 接口
      operationId: /admin/logout
      produces:
      - application/json
      summary: Admin Log out
      tags:
      - 管理员退出接口
swagger: "2.0"
